### ISSUE TITLE
Fix (possibly) memory-corrupting bug

### ISSUE THREAD

**Issue by matrefeytontias** [matrefeytontias/nKaruga-deprecated-Nspire-version-#13]
After running nKaruga a few times, the file manager will start to react slowly (key delays overwritten ?), and after some time Ndless will fail loading nKaruga, with the OS throwing the usual "format not supported" error.

**Comment by Vogtinator** [comment]
You've got some memory leaks in your code. If you store an array of Enemys in EnemysArray, the memory will never be freed if ~Enemy is "not supposed to happen". BTW: You don't have to say "G_enemies_array = new EnemiesArray;" in main, you can simply convert the global pointer to an object and everything will be correctly handled by the runtime.

**Comment by matrefeytontias** [comment]
~Enemy does happen when delete ~EnemiesArray is called, right ?

With Ndless 3.1 putting any object as global made Ndless fail to load the program. Didn't try with 3.6 though.

**Comment by Vogtinator** [comment]
Yes, that's one of the bugs I fixed in the SDK.

**Comment by matrefeytontias** [comment]
So is there actually any memory leak ? I just put "not supposed to happen" during that debugging session last night, and actually forgot to remove it, but it is called.

**Comment by Vogtinator** [comment]
If it's called than there is probably no memory leak, but try not to use malloc or new. Stack variables and global objects are the way to go, they will never leak if you try to follow RAII and you mostly do.

**Comment by matrefeytontias** [comment]
Okay, I'll change that. At least I'm happy that there doesn't seem to be memory leaks <_<
